server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/internet_banking #${JDBC_DATABASE_URL:}
    username: root #${JDBC_DATABASE_USERNAME:}
    password: 0868159243B#m #${JDBC_DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false

springdoc:
  swagger-ui:
    path: /docs

email:
  host: smtp.gmail.com
  port: 587
  username: hcmus.nhom04@gmail.com
  password: oixxgwffclltifel
  debug: true

internet-banking:
  app:
    jwt-secret: bimat
    jwt-duration: 900000 # 15 minutes
    jwt-refresh-duration: 604800000 # 7 days